# Generated by Django 4.2.1 on 2023-05-26 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['date', 'time']},
        ),
    ]
