# Generated by Django 4.2 on 2023-06-07 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0002_alter_flight_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passenger',
            options={'verbose_name': 'Passenger', 'verbose_name_plural': 'Passengers'},
        ),
    ]
